mitre-attack/attack-navigator

CHANGELOG.md
nav-app/src/app/exporter/exporter.component.html
nav-app/src/app/exporter/exporter.component.ts
nav-app/src/app/help/help.component.html

Add a control to the render window for visibility of sub-techniques in the rendered image

---

CHANGELOG.md
nav-app/src/app/viewmodels.service.ts

fixed #167 and #168

---

CHANGELOG.md
README.md

Add documentation of v2 instance

---

layers/data/update_layers/July_2020/July_2020_enterprise_attack.json
layers/data/update_layers/July_2020/July_2020_enterprise_attack_beta.json
layers/data/update_layers/July_2020/July_2020_mobile_attack.json
layers/data/update_layers/July_2020/July_2020_mobile_attack_beta.json
layers/data/update_layers/July_2020/README.md

Add update layers for the July 2020 ATT&CK release.

Add July 2020 update layers

---

.gitignore
layers/data/samples/APT3_+_APT29_with_software.json
layers/data/samples/APT3_+_APT29_with_software_and_notional_no_detection.json
layers/data/samples/Bear_APT.json
layers/data/samples/heatmap_layer.json
layers/data/samples/software_execution.json
layers/data/samples/software_malware_execution.json
layers/data/samples/software_tool_execution.json

update sample layers to use v7.0 data

---

layers/update-layers.py

Update the layer-update script to use v4.0 of the Layer schema.
Closes #235

Update the layer-updater script to use v4.0 of the Layer schema

---

layers/data/samples/Wizard_Spider-G0102-Updated.json

G0102 ATT&CK Navigator Layer with ATT&CK v8.0->v8.1 changes highlighted.

G0102 Layer with ATT&CK v8.0-V8.1 changes

---

nav-app/src/app/config.service.ts
nav-app/src/app/data.service.ts
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.ts

- Adds unsubscribes to all subscriptions to prevent possible memory leaks (from [here](https://blog.bitsrc.io/debugging-memory-leaks-in-angular-4bc7b3eab569)).
- Updates how the active tab is tracked to be more efficient and straightforward.

Additional performance improvements for tabs and data subscriptions

---

nav-app/src/app/config.service.ts

Fix for issue https://github.com/mitre-attack/attack-navigator/issues/265

Add global substitution for context menu variables

---

CHANGELOG.md
README.md
nav-app/src/app/config.service.ts
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.scss
nav-app/src/app/tabs/tabs.component.ts
nav-app/src/assets/config.json

Added banner placeholder in tabs component, and added banner feature in config.json

---

nav-app/src/app/data.service.ts
nav-app/src/app/datatable/data-table.component.html
nav-app/src/app/datatable/data-table.component.ts
nav-app/src/app/sidebar/layer-upgrade/layer-upgrade.component.ts

Updated sideBarOpened as a get set private variable in dataService, and updated the usage of it in the "done" button of the sidebar. I think this will be a good base for me to work off of for the issue that I'm working on [#204 search and multiselect](https://github.com/mitre-attack/attack-navigator/tree/feature/%23204-consolidate-search-and-multiselect).

Feature/#181 layer upgrade UI update

---

CHANGELOG.md
nav-app/angular.json
nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/app.module.ts
nav-app/src/app/cookies.ts
nav-app/src/app/datatable/data-table.component.html
nav-app/src/app/search-and-multiselect/search-popover-notification/search-popover-notification.component.html
nav-app/src/app/search-and-multiselect/search-popover-notification/search-popover-notification.component.scss
nav-app/src/app/search-and-multiselect/search-popover-notification/search-popover-notification.component.spec.ts
nav-app/src/app/search-and-multiselect/search-popover-notification/search-popover-notification.component.ts
nav-app/src/assets/config.json
nav-app/src/assets/icons/ic_playlist_add_black_24px.svg
nav-app/src/styles.scss

Adds a popover to the matrix view notifying the user that the search and multiselect interface have merged. 
This popover will only be shown:
- For the first month after the release
- If the user hasn't already seen it before

Notify the user that the search and multiselect interfaces have merged

---

CHANGELOG.md
nav-app/src/app/data.service.ts

Simple alert for external_id not found error

Added alert and throw console error when external id is not found in imported STIX data

---

CHANGELOG.md
nav-app/src/app/config.service.ts
nav-app/src/app/matrix/technique-cell/technique-cell.component.html
nav-app/src/assets/config.json

Allows users to disable the comment underline effect on techniques.
Resolves #268

Disable Comment Underline

---

CHANGELOG.md

Updated changelog with ui refactor change

---

CHANGELOG.md
nav-app/src/app/datatable/data-table.component.ts
nav-app/src/app/matrix/technique-cell/contextmenu/contextmenu.component.html
nav-app/src/app/matrix/technique-cell/contextmenu/contextmenu.component.ts
nav-app/src/app/matrix/technique-cell/technique-cell.component.ts
nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.html
nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.scss
nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.ts
nav-app/src/app/viewmodels.service.ts
nav-app/src/styles.scss

Allow user to scroll if comments overflow screen

---

.github/workflows/buildcheck.yml

Added github action to build angular app and check if build is passing

Add .github folder for actions workflows

---

README.md

Update README.md with new build bage

---

CHANGELOG.md
layers/LAYERFORMATv4_3.md
nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/data.service.ts
nav-app/src/assets/config.json

Fixes a bug caused by deprecated matrices (#473) and adds support for v11.3, including Mobile sub-techniques.

Support for ATT&CK v11.3 and Mobile sub-techniques

---

CHANGELOG.md
nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/exporter/exporter.component.ts
nav-app/src/app/viewmodels.service.ts

494 svg exporter does not honor sort selection

---

CHANGELOG.md
USAGE.md
layers/LAYERFORMATv4_4.md
nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/config.service.ts
nav-app/src/app/data.service.ts
nav-app/src/app/datatable/data-table.component.html
nav-app/src/app/datatable/data-table.component.ts
nav-app/src/app/globals.ts
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.scss
nav-app/src/app/tabs/tabs.component.ts
nav-app/src/app/viewmodels.service.ts

load collection or stix bundle from url

---

CHANGELOG.md
USAGE.md
nav-app/src/app/matrix/cell.ts
nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.html
nav-app/src/app/viewmodels.service.ts

Updates to only calculate aggregate scores on techniques with sub-techniques.
Resolves #539

Bug fix for aggregate scores

---

nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.html
nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.scss
nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.ts
nav-app/src/colors.scss

Added an "unpin" option to pinned tooltip

---

CHANGELOG.md
layers/LAYERFORMATv4_5.md
nav-app/src/app/datatable/data-table.component.html
nav-app/src/app/globals.ts
nav-app/src/app/services/viewmodels.service.ts

Added ability to only select visible techniques. Changes include: 
- New selection behavior option "select only visible techniques".
- When selected, hidden techniques are omitted from any selection behavior.

New Selection Behavior Option: Select Only Visible Techniques

---

CHANGELOG.md
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.scss

This pull request addresses #580.
Users should now be able to scroll across the open tabs in the navigator.

Added scroll bar to the tabs container

---

nav-app/src/app/classes/index.ts
nav-app/src/app/classes/tab.ts
nav-app/src/app/classes/view-model.ts
nav-app/src/app/services/viewmodels.service.ts
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.scss
nav-app/src/app/tabs/tabs.component.ts
nav-app/src/assets/config.json

Summary of changes:
- Refactors the tab component
- Fixes the header/banner configurations, such that the "help"/"changelog" buttons will now still show up if a banner is displayed
- Removes use of tables for layout purposes (this is a discouraged practice)
- Cleanup tabs SCSS

Refactor tabs & fix banner

---

CHANGELOG.md
nav-app/src/app/layer-upgrade/layer-upgrade.component.html
nav-app/src/app/list-input/list-input.component.html
nav-app/src/app/search-and-multiselect/search-and-multiselect.component.html

527 reverse tabnabbing

---

CHANGELOG.md
nav-app/src/app/matrix/cell.ts
nav-app/src/app/matrix/matrix-common.ts
nav-app/src/app/matrix/matrix-flat/matrix-flat.component.scss
nav-app/src/app/matrix/matrix-side/matrix-side.component.scss

This pull request addresses #404.
Added functionality to scroll down with the Tactics header frozen to the top.

Freeze the tactic row

---

nav-app/src/app/svg-export/svg-export.component.spec.ts

Added additional tests for svg export component

Draft: SVG export updated Tests

---

CHANGELOG.md
nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/classes/stix/technique.ts
nav-app/src/app/services/data.service.ts

Fix for 620 - issues loading layers v10 and earlier

---

CHANGELOG.md
nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/classes/stix/data-component.ts

622 select by data source

---

CHANGELOG.md
nav-app/src/app/tabs/tabs.component.spec.ts
nav-app/src/app/tabs/tabs.component.ts

624 bug loading multi-layer JSON via embedded links
