nav-app/src/app/tabs/tabs.component.ts

Sets the correct tab name when loading a default layer (and all other uses of loadLayerFromLocalFile).
Proposed fix for #54

Correct tab name for loadLayerFromLocalFile

---

CHANGELOG.md
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.ts

Fixes the bug in the "create customized Navigator" interface in which the layer URL input field loses focus after each typed character and appends the character to subsequent URLs.
Resolves Issue #136

Fix for layer URL inputs

---

CHANGELOG.md
nav-app/src/app/data.service.ts
nav-app/src/app/multiselect/multiselect.component.ts
nav-app/src/app/techniques-search/techniques-search.component.ts

Removes duplicate threat group entries from the multiselect interface. Sub-techniques are also included when selecting techniques associated with threat groups, software, and mitigations.
Resolves Issue #164

Bug fixes for multiselect interface

---

CHANGELOG.md
nav-app/src/app/help/help.component.html
nav-app/src/app/matrix/technique-cell/contextmenu/contextmenu.component.html
nav-app/src/app/matrix/technique-cell/contextmenu/contextmenu.component.ts
nav-app/src/app/viewmodels.service.ts

Adds two buttons to the context menu to select annotated or select unannotated techniques and sub-techniques.
Resolves Issue #163

Select techniques with/without annotations

---

README.md
nav-app/src/app/exporter/exporter.component.html
nav-app/src/app/help/help.component.html
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.scss
nav-app/src/app/tabs/tabs.component.ts
nav-app/src/styles.scss

Removes Safari support
- Adds a prompt to warn Safari users that the browser no longer supported
- Removes Safari from the help page and the list of supported browsers

Remove safari support

---

nav-app/src/app/app.component.html
nav-app/src/app/app.component.ts
nav-app/src/app/datatable/data-table.component.html
nav-app/src/app/datatable/data-table.component.scss
nav-app/src/app/datatable/data-table.component.ts

Moved sidebar to inside matrix layout, rather than outside as overlay on top of app

Feature/#181 layer upgrade UI update

---

CHANGELOG.md
README.md
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.ts

Fix uses the existing `is_js `dependency.
This fix was tested using the Safari browser's Develop tool (via user agent in the menu) to run the app using version 13.0 and 14.0 on my Mac. It doesn't seem possible to downgrade Safari versions, so this seems to be the best way of testing it.

Added check for if Safari version is 13. and below to show incompatibility warning dialog

---

nav-app/src/app/data.service.ts
nav-app/src/app/layer-upgrade/changelog-cell/changelog-cell.component.ts
nav-app/src/app/layer-upgrade/layer-upgrade.component.scss
nav-app/src/app/tabs/tabs.component.ts

Includes bug fixes for the layer upgrade workflow:
- Fixed bug where selecting techniques in the interface behaved as a "shift + click" selection, which caused the selections to accumulate rather than selecting one technique at a time.
- Fixed a bug where uploading an outdated layer without upgrading to the latest version would omit revoked/deprecated objects, causing any subsequent layer upgrades to be missing objects in the version comparison.
- Added styling for the technique loading spinners in the workflow steps.

Layer upgrade fixes

---

CHANGELOG.md
nav-app/src/app/viewmodels.service.ts

Resolves #354. Layers which defined annotations on revoked/deprecated techniques without explicitly defining their tactics could previously crash the application when loaded, since the tactics of a revoked/deprecated technique cannot always be inferred due to the ATT&CK data model. 
The bug was introduced with v4.4 of the Navigator, which changed the handling of revoked/deprecated objects due to requirements of the layer upgrade workflow.
With this PR annotations will not be loaded for revoked/deprecated techniques in the first place, avoiding the crash.

fix for #354: avoid loading revoked/deprecated techniques from layer

---

CHANGELOG.md
README.md
USAGE.md
nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/globals.ts
nav-app/src/app/tabs/tabs.component.ts

Fixes #361. Previously, the await for the first layer to be loaded never resolved, so the application would never attempt to load additional layers. Now the system waits for each layer to finish loading completely (including fetching the STIX data and upgrading layers) before resolving so that the next layer can attempt to load.
Also updates the app version number to v4.5.2.

Fix loading for multiple layers

---

nav-app/src/app/matrix/cell.ts
nav-app/src/app/viewmodels.service.ts

Patch for #375.
- Updates the cell color and cell text color code to emulate an alpha channel on non hex8 formatted colors
- Updates the gradient serialization code to save hex8 formatted colors in exported gradients (otherwise alpha would not be saved in exported gradients).
Test layer using alpha gradients:
```json
{
"name": "layer",
"versions": {
"attack": "10",
"navigator": "4.5.1",
"layer": "4.2"
},
"domain": "enterprise-attack",
"description": "",
"filters": {
"platforms": [
"Linux",
"macOS",
"Windows",
"Azure AD",
"Office 365",
"SaaS",
"IaaS",
"Google Workspace",
"PRE",
"Network",
"Containers"
]
},
"sorting": 0,
"layout": {
"layout": "side",
"aggregateFunction": "average",
"showID": false,
"showName": true,
"showAggregateScores": false,
"countUnscored": false
},
"hideDisabled": …
```

Add support for alpha in gradients

---

CHANGELOG.md
nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/matrix/cell.ts

Fixes #388 where unscored techniques (when show aggregate scores is enabled) would have a black background color, making it hard to see in the light color theme

Fixed incorrect technique cell background color when aggregate score is an empty string

---

.dockerignore
Dockerfile
README.md
nav-app/package-lock.json

This looks like it should address #391 for two reasons:
1. That issue was "simple" in that all that was needed to fix it was downgrading the base docker image from `node:latest` to `node:16` (the latest LTS version at this time).
2. The new issue was that there was a JavaScript heap out of memory problem. This addresses that issue as well (more details on that in #391... soon)

Fix dockerfile

---

nav-app/src/app/exporter/exporter.component.ts

Addresses #221 by setting 
- Cell text, i.e. technique/subtechnique names, to the same minimum optimal font size
- Tactic labels have their own consistent minimum optimal font size
- Header text max size is now 12 instead of 32 to better match the rest of the font sizes, open to thoughts
Use case: looking to have a consistent custom matrix representation for inclusion in a paper/poster.
Screenshot of SVG export of the default enterprise layer on this branch:
Compared to existing output:
Screenshot of SVG export of the default enterprise layer on `develop`:

Consistent font sizes for SVG export

---

nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.scss

Break-up lines in technique cell tooltip to prevent overflow outside of tooltip box

---

Dockerfile

Closes #497 
This Issue is triggered by package dependency `@angular-devkit/build-angular@0.1100.7`. 
```
npm ERR! Conflicting peer dependency: karma@5.1.1
npm ERR! node_modules/karma
npm ERR!   peerOptional karma@"~5.1.0" from @angular-devkit/build-angular@0.1100.7
```
If we check the peer dependencies of `@angular-devkit/build-angular@0.1100.7`:
```
➜npm info @angular-devkit/build-angular@0.1100.7 peerDependencies
{
'@angular/compiler-cli': '^11.0.0',
'@angular/localize': '^11.0.0',
karma: '~5.1.0',  <--- HERE IS THE CONFLICT
'ng-packagr': '^11.0.0',
protractor: '^7.0.0',
tslint: '^6.1.0',
typescript: '~4.0.0'
}
```
However, upgrading `karma` to 5.1.0 is currently impossible on `@angular/core@11.2.14`. We would need to upgrade to version 12 for this to work.
```
➜npm install …
```

497 running error step 811 run npm install unsafe perm

---

nav-app/src/app/data.service.ts

When creating a Matrix object, filters out references to tactics that aren't included in the source content.

Ignore a matrix's references to tactics that aren't in the source content

---

CHANGELOG.md
nav-app/src/app/matrix/cell.ts
nav-app/src/assets/config.json

Adds the following three color options to "create a customized navigator"  technique controls.
- Enable/disable displaying colors for aggregate scores
- Enable/disable displaying colors for non-aggregate scores
- Enable/disable displaying manually assigned colors
Resolves [#371](https://github.com/mitre-attack/attack-navigator/issues/371)

Add additional color options

---

nav-app/src/app/exporter/exporter.component.html
nav-app/src/styles.scss

When using Navigator in dark mode, under "render layer to SVG", "image size", the unit suffix for "header height" is black. Additionally, the placeholder text for all the dropdown menus under "render layer to SVG" are black (font, sub-techniques, etc.). This changes their colors to white to match the styling of the rest of the toolbar.

SVG toolbar dark mode colors

---

nav-app/src/app/exporter/exporter.component.html
nav-app/src/app/exporter/exporter.component.ts

Added two additional image size options in the "render layer to SVG" toolbar. Users can select from a variety of different svg size options, including "custom" and can set the size to either "landscape" or "portrait".

SVG size and orientation options

---

Dockerfile
README.md

Node.js 16 has now reached maintenance mode and will reach end-of-life on 2023-09-11. The new LTS version is Node.js 18. Updates the Dockerfile to use Node.js 18.
Resolves https://github.com/mitre-attack/attack-navigator/issues/540

Update Node.js 16 to 18 

---

nav-app/src/app/datatable/data-table.component.html
nav-app/src/app/datatable/data-table.component.scss
nav-app/src/app/datatable/data-table.component.ts
nav-app/src/app/services/viewmodels.service.ts

Includes the following changes to the toolbar's export features:
- Consolidates all three export options into a single dropdown
- Includes option to only download annotations on visible techniques
- Displays warning text if there are hidden techniques that are annotated 
Resolves https://github.com/mitre-attack/attack-navigator/issues/215

Updated Download/Export Feature

---

CHANGELOG.md
nav-app/src/app/svg-export/renderable-objects/renderable-technique.ts
nav-app/src/app/svg-export/svg-export.component.html
nav-app/src/app/svg-export/svg-export.component.scss
nav-app/src/app/svg-export/svg-export.component.ts

Added ability to render SVG export in dark theme. Changes include: 
- Toggle button on SVG exporter toolbar to switch between dark and light theme
Resolves https://github.com/mitre-attack/attack-navigator/issues/556

Dark Theme for SVG

---

CHANGELOG.md
nav-app/src/app/matrix/cell.ts
nav-app/src/app/services/config.service.ts
nav-app/src/assets/config.json

This pull request addresses part of #400. The user should now be able to select whether or not to display the metadata underline either by changing the config file or by using the customized navigator.

Metadata underline

---

CHANGELOG.md
layers/LAYERFORMATv4_5.md
nav-app/src/app/classes/layout-options.ts
nav-app/src/app/classes/view-model.ts
nav-app/src/app/datatable/data-table.component.ts

This pull request address #560 
Users should now be able to configure how to display sub techniques in the layer file - annotated, all, or none
Includes the metadata_underline change

Expand annotated subtechniques

---

nav-app/src/app/svg-export/svg-export.component.html
nav-app/src/app/svg-export/svg-export.component.ts

Added the ability for users to set the font size of the SVG export. Changes include:
- New "auto-fit font size" button, which calculates the most visually appealing font size
- New font size input, which allows users to manually change the SVG font size
- Warning message if the font size is increased such that the text overflows outside of any of the cells
Resolves https://github.com/mitre-attack/attack-navigator/issues/484

Option to Change SVG Font Size

---

nav-app/package-lock.json

- Bumps `@angular-devkit/build-angular` from 14.2.12 to 14.2.13
- Bumps `@angular/cli` from 14.2.12 to 14.2.13
- Bumps `@babel/runtime` from 7.22.6 to 7.23.2
- Bumps `@fontsource/roboto` from 5.0.7 to 5.0.8
- Bumps `@fontsource/roboto-mono` from 5.0.7 to 5.0.13
- Bumps `@types/file-saver` from 2.0.5 to 2.0.6
- Bumps `@types/jasmine` from 4.3.5 to 4.6.1
- Bumps `@types/jasminewd2` from 2.0.10 to 2.0.12
- Bumps `@types/node` from 18.17.1 to 18.18.6
- Bumps `core-js` from 3.32.0 to 3.33.0
- Bumps `fsevents` from 2.3.2 to 2.3.3
- Bumps `jasmine-core` from 5.1.0 to 5.1.1
- Bumps `tslib` from 2.6.1 to 2.6.2

Package updates

---

nav-app/src/app/app.component.spec.ts
nav-app/src/app/app.module.ts
nav-app/src/app/layer-upgrade/changelog-cell/changelog-cell.component.html
nav-app/src/app/layer-upgrade/changelog-cell/changelog-cell.component.spec.ts
nav-app/src/app/matrix/cell.ts
nav-app/src/app/matrix/matrix-flat/matrix-flat.component.spec.ts
nav-app/src/app/matrix/technique-cell/technique-cell.component.spec.ts
nav-app/src/app/services/config.service.spec.ts
nav-app/src/app/services/config.service.ts
nav-app/src/app/services/data.service.spec.ts
nav-app/src/app/services/data.service.ts
nav-app/src/app/services/viewmodels.service.spec.ts
nav-app/src/app/tabs/tabs.component.html
nav-app/src/app/tabs/tabs.component.spec.ts
nav-app/src/app/tabs/tabs.component.ts
nav-app/src/tests/utils/mock-data.ts

- Refactors the configuration service for improved configuration file loading on app startup.
- Removes unused/legacy functions.
- Updates unit tests to use startup configuration.

Refactor ConfigService

---

nav-app/src/app/classes/stix/domain.ts
nav-app/src/app/layer-information/layer-information.component.ts
nav-app/src/app/services/data.service.ts

618 layer upgrade UI bug

---

nav-app/package-lock.json
nav-app/package.json
nav-app/src/app/datatable/data-table.component.ts
nav-app/src/app/services/viewmodels.service.ts
nav-app/src/app/svg-export/svg-export.component.ts
nav-app/src/app/tabs/tabs.component.spec.ts
nav-app/src/app/tabs/tabs.component.ts
nav-app/src/app/utils/utils.ts

Replaces `is_js` which appears to be no longer maintained. See [`is_js` GitHub Advisory](https://github.com/advisories/GHSA-pvrw-g6fx-mcx2).

Replace `is_js` library
